Description: Master stack which creates all required nested stacks

Parameters:
  TemplatePath:
    Type: String
    Default: sandbox01-demo-iad/templates/
    Description: S3Bucket Path where the templates are stored, in the form BUCKET_NAME/[FOLDER/]
  VPC:
    Type: AWS::EC2::VPC::Id
  SubnetA:
    Type: AWS::EC2::Subnet::Id
  SubnetB:
    Type: AWS::EC2::Subnet::Id
  Image:
    Type: String
    Default: 331780945983.dkr.ecr.us-east-1.amazonaws.com/my-wordpress:b2c866a
  ServiceName:
    Type: String
    Default: my-wordpress-iad-prod
  ContainerPort:
    Type: Number
    Default: 80
  LoadBalancerPort:
    Type: Number
    Default: 80
  HealthCheckPath:
    Type: String
    Default: /
  MinContainers:
    Type: Number
    Default: 2
  MaxContainers:
    Type: Number
    Default: 10
  AutoScalingTargetValue:
    Type: Number
    Default: 50

  DatabaseHost:
    Type: String 

  DBSubnetGroup:
    Type: String
    Description: Enter a valid DB Subnet Group
  DatabaseUser:
    AllowedPattern: "[a-zA-Z0-9]+"
    ConstraintDescription: must be between 1 to 16 alphanumeric characters.
    Description: The database admin account user name, between 1 to 16 alphanumeric characters.
    MaxLength: '16'
    MinLength: '1'
    Type: String
  DatabasePassword:
    AllowedPattern: "[a-zA-Z0-9]+"
    ConstraintDescription: must be between 8 to 41 alphanumeric characters.
    Description: The database admin account password, between 8 to 41 alphanumeric characters.
    MaxLength: '41'
    MinLength: '8'
    NoEcho: 'true'
    Type: String
  DatabaseInstanceClass:
    Type: String
    AllowedValues:
      - db.t2.small
      - db.t2.medium
      - db.t2.large
    Default: db.t2.small
  SubnetIds:
    Type: 'List<AWS::EC2::Subnet::Id>'
  ClientSecurityGroupIds:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'

Resources:

  ServerStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub: "https://s3.amazonaws.com/${TemplatePath}fargate-ecs.yaml"
      Parameters:
        VPC:
          Ref: VPC
        SubnetA:
          Ref: SubnetA
        SubnetB:
          Ref: SubnetB
        Image:
          Ref: Image
        ServiceName:
          Ref: ServiceName
        ContainerPort:
          Ref: ContainerPort
        LoadBalancerPort:
          Ref: LoadBalancerPort
        HealthCheckPath:
          Ref: HealthCheckPath
        MinContainers:
          Ref: MinContainers
        MaxContainers:
          Ref: MaxContainers
        AutoScalingTargetValue:
          Ref: AutoScalingTargetValue
        DatabaseHost:
          Ref: DatabaseHost 
        DatabasePassword:
          Ref: DatabasePassword
        DatabaseUser:
          Ref: DatabaseUser
Outputs:
  WebELBURL:
    Description: "URL endpoint of web ELB"
    Value:
      Fn::GetAtt: ServerStack.Outputs.LoadBalancerUrl
