Description: Master stack which creates all required nested stacks

Parameters:
  TemplatePath:
    Type: String
    Default: sandbox01-demo-iad/templates/
    Description: S3Bucket Path where the templates are stored, in the form BUCKET_NAME/[FOLDER/]
  VPC:
    Type: AWS::EC2::VPC::Id
  SubnetA:
    Type: AWS::EC2::Subnet::Id
  SubnetB:
    Type: AWS::EC2::Subnet::Id
  Image:
    Type: String
    Default: 331780945983.dkr.ecr.us-east-1.amazonaws.com/my-wordpress:b2c866a
  ServiceName:
    Type: String
    Default: my-wordpress-iad-prod
  ContainerPort:
    Type: Number
    Default: 80
  LoadBalancerPort:
    Type: Number
    Default: 80
  HealthCheckPath:
    Type: String
    Default: /
  Subdomain:
    Type: String
    Default: my-wordpress
  MinContainers:
    Type: Number
    Default: 2
  MaxContainers:
    Type: Number
    Default: 10
  AutoScalingTargetValue:
    Type: Number
    Default: 50

  DatabaseHost:
    Type: String 

  DBSubnetGroup:
    Type: String
    Description: Enter a valid DB Subnet Group
  DatabaseUser:
    Type: String
    Description: Enter a valid Database master username
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
  DatabasePassword:
    Type: String
    Description: Enter a valid Database master password
    NoEcho: true
    MinLength: 1
    MaxLength: 41
    AllowedPattern: "[a-zA-Z0-9]*"
  DBInstanceType:
    Type: String
    Description: Enter one of the possible instance type for database
    AllowedValues:
      - db.t2.micro
      - db.t2.small
      - db.t2.medium
      - db.t2.large
    Default: db.t2.small
  Environment:
    Type: String
    Description: Select the appropriate environment
    AllowedValues:
      - dev
      - test
      - uat
      - prod
    Default: prod

Resources:

  ServerStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub: "https://s3.amazonaws.com/${TemplatePath}fargate-ecs.yaml"
        #Fn::Sub: "https://s3.amazonaws.com/sandbox01-demo-iad/templates/fargate-ecs.yaml"
      Parameters:
        VPC:
          Ref: VPC
        SubnetA:
          Ref: SubnetA
        SubnetB:
          Ref: SubnetB
        Image:
          Ref: Image
        ServiceName:
          Ref: ServiceName
        ContainerPort:
          Ref: ContainerPort
        LoadBalancerPort:
          Ref: LoadBalancerPort
        HealthCheckPath:
          Ref: HealthCheckPath
        Subdomain:
          Ref: Subdomain
        MinContainers:
          Ref: MinContainers
        MaxContainers:
          Ref: MaxContainers
        AutoScalingTargetValue:
          Ref: AutoScalingTargetValue
        DatabaseHost:
          Ref: DatabaseHost 
        DatabasePassword:
          Ref: DatabasePassword
        DatabaseUser:
          Ref: DatabaseUser
Outputs:
  WebELBURL:
    Description: "URL endpoint of web ELB"
    Value:
      Fn::GetAtt: ServerStack.Outputs.LoadBalancerUrl
