Description: Master stack which creates all required nested stacks

Parameters:
  TemplatePath:
    Type: String
    Default: sandbox01-demo-iad/templates/
    Description: S3Bucket Path where the templates are stored, in the form BUCKET_NAME/[FOLDER/]
  VPC:
    Type: AWS::EC2::VPC::Id
  SubnetA:
    Type: AWS::EC2::Subnet::Id
  SubnetB:
    Type: AWS::EC2::Subnet::Id
  Image:
    Type: String
    Default: 331780945983.dkr.ecr.us-east-1.amazonaws.com/my-wordpress:b2c866a
  ServiceName:
    Type: String
    Default: my-wordpress-iad-prod
  ContainerPort:
    Type: Number
    Default: 80
  LoadBalancerPort:
    Type: Number
    Default: 80
  HealthCheckPath:
    Type: String
    Default: /
  MinContainers:
    Type: Number
    Default: 2
  MaxContainers:
    Type: Number
    Default: 10
  AutoScalingTargetValue:
    Type: Number
    Default: 50
  DatabaseUser:
    AllowedPattern: "[a-zA-Z0-9]+"
    ConstraintDescription: must be between 1 to 16 alphanumeric characters.
    Description: The database admin account user name, between 1 to 16 alphanumeric characters.
    MaxLength: '16'
    MinLength: '1'
    Type: String
  DatabasePassword:
    AllowedPattern: "[a-zA-Z0-9]+"
    ConstraintDescription: must be between 8 to 41 alphanumeric characters.
    Description: The database admin account password, between 8 to 41 alphanumeric characters.
    MaxLength: '41'
    MinLength: '8'
    NoEcho: 'true'
    Type: String
  DatabaseInstanceClass:
    Type: String
    AllowedValues:
      - db.t2.small
      - db.t2.medium
      - db.t2.large
    Default: db.t2.small

Resources:

  SecurityStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub: "https://s3.amazonaws.com/${TemplatePath}fargate-security.yaml"
      Parameters:
        VPC:
          Ref: VPC
        ServiceName:
          Ref: ServiceName
        ContainerPort:
          Ref: ContainerPort
        LoadBalancerPort:
          Ref: LoadBalancerPort

  DatabaseStack:
    DependsOn: SecurityStack
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub: "https://s3.amazonaws.com/${TemplatePath}fargate-rds.yaml"
      Parameters:
        DatabaseUser:
          Ref: DatabaseUser
        DatabasePassword:
          Ref: DatabasePassword
        SubnetA:
          Ref: SubnetA
        SubnetB:
          Ref: SubnetB
        ClientSecurityGroupId: # "sg-0a5bfb2723b54d97e"
          Fn::GetAtt: [ SecurityStack, Outputs.ContainerSecurityGroup ]
        DatabaseInstanceClass: db.t2.small

  ComputeStack:
    DependsOn: [ SecurityStack, DatabaseStack ]
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub: "https://s3.amazonaws.com/${TemplatePath}fargate-ecs.yaml"
      Parameters:
        VPC:
          Ref: VPC
        SubnetA:
          Ref: SubnetA
        SubnetB:
          Ref: SubnetB
        Image:
          Ref: Image
        ServiceName:
          Ref: ServiceName
        ContainerSecurityGroup:
          Fn::GetAtt: [ SecurityStack, Outputs.ContainerSecurityGroup ]
        LoadBalancerSecurityGroup:
          Fn::GetAtt: [ SecurityStack, Outputs.LoadBalancerSecurityGroup ]
        ContainerPort:
          Ref: ContainerPort
        LoadBalancerPort:
          Ref: LoadBalancerPort
        HealthCheckPath:
          Ref: HealthCheckPath
        MinContainers:
          Ref: MinContainers
        MaxContainers:
          Ref: MaxContainers
        AutoScalingTargetValue:
          Ref: AutoScalingTargetValue
        DatabaseHost:
          GetAtt: DatabaseStack, Outputs.DatabaseClusterEndpoint
        DatabasePassword:
          Ref: DatabasePassword
        DatabaseUser:
          Ref: DatabaseUser

Outputs:
  WebELBURL:
    Description: "URL endpoint of web ELB"
    Value:
      Fn::GetAtt: ComputeStack.Outputs.LoadBalancerUrl
